import Phaser from "phaser";
import type { OrbitscarContent } from "@orbitscar/content";
import type { ColonyState, OrbitscarBattleEvent, OrbitscarBattleResult, OrbitscarPosition } from "@orbitscar/simulation";
import { type GameMode, type ReplayState, type Zone, zonePositions } from "../state/game-session.js";

const ARENA = { width: 1200, height: 800 };
const GRID = 40;
export type SceneBridge = { content: OrbitscarContent; getMode: () => GameMode; getColony: () => ColonyState; getBuildMode: () => string | undefined; getSelectedBuildingId: () => string | undefined; getSelectedZone: () => Zone; getTargetStructures: () => Array<{ id: string; buildingId: string; position: OrbitscarPosition; currentHealth?: number }>; getReplay: () => ReplayState | undefined; setPreview: (position?: OrbitscarPosition) => void; selectBuilding: (id?: string) => void; selectZone: (zone: Zone) => void; placeBuilding: (position: OrbitscarPosition) => void; onFrame: (now: number) => void };

export class OrbitscarScene extends Phaser.Scene {
  private world!: Phaser.GameObjects.Graphics;
  private bridge!: SceneBridge;
  private dragStart?: { x: number; y: number; scrollX: number; scrollY: number };
  private pinchDistance?: number;
  private preview?: OrbitscarPosition;
  private units = new Map<string, { position: OrbitscarPosition; health: number; alive: boolean }>();
  private structureHealth = new Map<string, number>();
  constructor(bridge: SceneBridge) { super("OrbitscarScene"); this.bridge = bridge; }
  create(): void {
    this.world = this.add.graphics();
    this.cameras.main.setBounds(0, 0, ARENA.width, ARENA.height);
    this.updateCameraZoom();
    this.input.addPointer(2);
    this.input.on("pointerdown", (pointer: Phaser.Input.Pointer) => { if (this.input.pointer1.isDown && this.input.pointer2.isDown) { this.pinchDistance = this.pointerDistance(); this.dragStart = undefined; return; } const point = this.worldPoint(pointer); this.preview = point; this.bridge.setPreview(point); this.dragStart = { x: pointer.x, y: pointer.y, scrollX: this.cameras.main.scrollX, scrollY: this.cameras.main.scrollY }; });
    this.input.on("pointermove", (pointer: Phaser.Input.Pointer) => { const point = this.worldPoint(pointer); this.preview = point; this.bridge.setPreview(point); if (this.input.pointer1.isDown && this.input.pointer2.isDown) { const distance = this.pointerDistance(); if (this.pinchDistance && distance > 0) this.cameras.main.setZoom(Phaser.Math.Clamp(this.cameras.main.zoom * (distance / this.pinchDistance), .55, 2)); this.pinchDistance = distance; return; } if (!this.dragStart || !pointer.isDown) return; this.cameras.main.scrollX = this.dragStart.scrollX - (pointer.x - this.dragStart.x) / this.cameras.main.zoom; this.cameras.main.scrollY = this.dragStart.scrollY - (pointer.y - this.dragStart.y) / this.cameras.main.zoom; });
    this.input.on("pointerup", (pointer: Phaser.Input.Pointer) => { const wasTap = this.dragStart !== undefined && Math.abs(pointer.x - this.dragStart.x) < 8 && Math.abs(pointer.y - this.dragStart.y) < 8; const point = this.worldPoint(pointer); this.dragStart = undefined; if (!this.input.pointer1.isDown || !this.input.pointer2.isDown) this.pinchDistance = undefined; if (!wasTap) return; if (this.bridge.getMode() === "colony") this.colonyClick(point); else if (this.bridge.getMode() === "deployment") this.battleClick(point); });
    this.input.on("wheel", (_pointer: Phaser.Input.Pointer, _objects: Phaser.GameObjects.GameObject[], _dx: number, dy: number) => this.cameras.main.setZoom(Phaser.Math.Clamp(this.cameras.main.zoom - dy * .001, .55, 2)));
    this.scale.on("resize", () => this.updateCameraZoom());
    this.draw();
  }
  update(): void { this.bridge.onFrame(performance.now()); this.draw(); }
  private worldPoint(pointer: Phaser.Input.Pointer): OrbitscarPosition { const point = this.cameras.main.getWorldPoint(pointer.x, pointer.y); return { x: point.x, y: point.y }; }
  private pointerDistance(): number { return Phaser.Math.Distance.Between(this.input.pointer1.x, this.input.pointer1.y, this.input.pointer2.x, this.input.pointer2.y); }
  private updateCameraZoom(): void { if (this.cameras.main) this.cameras.main.setZoom(Phaser.Math.Clamp(Math.min(this.scale.width / ARENA.width, this.scale.height / ARENA.height), .55, 1.5)); }
  private colonyClick(point: OrbitscarPosition): void { const buildMode = this.bridge.getBuildMode(); if (buildMode) { this.bridge.placeBuilding({ x: Math.round((point.x - 20) / GRID) * GRID, y: Math.round((point.y - 20) / GRID) * GRID }); return; } const colony = this.bridge.getColony(); const hit = [...colony.buildings].reverse().find((building) => { const footprint = this.bridge.content.buildings[building.buildingId].footprint; return point.x >= building.position.x && point.x <= building.position.x + footprint[0] * GRID && point.y >= building.position.y && point.y <= building.position.y + footprint[1] * GRID; }); this.bridge.selectBuilding(hit?.id); }
  private battleClick(point: OrbitscarPosition): void { const hit = (Object.entries(zonePositions) as [Zone, OrbitscarPosition][]).find(([, position]) => Math.abs(point.x - position.x) < 80 && Math.abs(point.y - position.y) < 80); if (hit) this.bridge.selectZone(hit[0]); }
  private applyEvents(events: OrbitscarBattleEvent[], replay: ReplayState): void { this.units.clear(); this.structureHealth.clear(); for (const structure of replay.input.structures) this.structureHealth.set(structure.id, structure.currentHealth ?? this.bridge.content.buildings[structure.buildingId].maxHealth); for (const event of events) { if (event.entityId?.includes("#")) { const unitId = event.entityId.split("#")[0]; const unit = this.units.get(event.entityId) ?? { position: event.position ?? { x: 0, y: 0 }, health: this.bridge.content.units[unitId].health, alive: true }; if (event.position) unit.position = { ...event.position }; if (event.remainingHealth !== undefined) unit.health = event.remainingHealth; if (event.type === "unit_destroyed") unit.alive = false; this.units.set(event.entityId, unit); } else if (event.entityId && event.remainingHealth !== undefined) this.structureHealth.set(event.entityId, event.remainingHealth); } }
  private draw(): void { if (!this.world) return; this.world.clear(); this.world.fillStyle(0x09151c, 1).fillRect(0, 0, ARENA.width, ARENA.height); this.world.lineStyle(1, 0x17323c, 1); for (let x = 0; x <= ARENA.width; x += GRID) this.world.lineBetween(x, 0, x, ARENA.height); for (let y = 0; y <= ARENA.height; y += GRID) this.world.lineBetween(0, y, ARENA.width, y); if (this.bridge.getMode() === "colony") this.drawColony(); else this.drawBattle(); }
  private drawColony(): void { this.world.fillStyle(0x18363d, .65).fillRoundedRect(90, 100, 700, 600, 18); const colony = this.bridge.getColony(); for (const building of colony.buildings) { const definition = this.bridge.content.buildings[building.buildingId]; const w = definition.footprint[0] * GRID; const h = definition.footprint[1] * GRID; const selected = this.bridge.getSelectedBuildingId() === building.id; const color = building.buildingId === "command_relay" ? 0xf2c879 : definition.defenseId ? 0xe07878 : 0x7396a3; this.world.fillStyle(color, .9).fillRect(building.position.x, building.position.y, w, h); this.world.lineStyle(selected ? 4 : 2, selected ? 0xffffff : 0x0b1115, 1).strokeRect(building.position.x, building.position.y, w, h); this.world.fillStyle(0x071017, .7).fillRect(building.position.x, building.position.y + h - 9, w, 9); this.world.fillStyle(0x8ee6d1, 1).fillRect(building.position.x, building.position.y + h - 9, w * Math.min(1, building.health / (definition.maxHealth * (1 + (building.level - 1) * .25))), 9); } const buildMode = this.bridge.getBuildMode(); if (buildMode && this.preview) { const definition = this.bridge.content.buildings[buildMode]; this.world.lineStyle(2, 0x8ee6d1, .9).strokeRect(this.preview.x, this.preview.y, definition.footprint[0] * GRID, definition.footprint[1] * GRID); } }
  private drawBattle(): void { for (const [zone, position] of Object.entries(zonePositions) as [Zone, OrbitscarPosition][]) this.drawZone(zone, position); const replay = this.bridge.getReplay(); if (replay) this.applyEvents(replay.result.events.slice(0, replay.eventIndex), replay); const structures = replay?.input.structures ?? this.bridge.getTargetStructures(); for (const structure of structures) this.drawStructure(structure); if (replay) { for (const [id, unit] of this.units) if (unit.alive) { const color = id.startsWith("ram_walker") ? 0xf2c879 : id.startsWith("needle_drone") ? 0x8ee6d1 : 0x9bb7ff; this.world.fillStyle(color, 1).fillCircle(unit.position.x, unit.position.y, 9); this.world.lineStyle(1, 0x071017, 1).strokeCircle(unit.position.x, unit.position.y, 12); } } }
  private drawZone(zone: Zone, position: OrbitscarPosition): void { const selected = zone === (this.bridge.getMode() === "deployment" ? this.bridge.getSelectedZone() : this.bridge.getReplay()?.input.commands.find((command) => command.type === "DEPLOY")?.payload.zone); this.world.fillStyle(selected ? 0x1d796e : 0x16414a, selected ? .35 : .18).fillRect(position.x - 70, position.y - 70, 140, 140); this.world.lineStyle(2, selected ? 0x8ee6d1 : 0x32606b, .8).strokeRect(position.x - 70, position.y - 70, 140, 140); }
  // maxHealth always comes from the content definition; the caller passes the
  // structure record so current damage can never be mistaken for the maximum.
  private drawStructure(structure: { id: string; buildingId: string; position: OrbitscarPosition; currentHealth?: number }): void { const maxHealth = this.bridge.content.buildings[structure.buildingId].maxHealth; const health = this.structureHealth.get(structure.id) ?? structure.currentHealth ?? maxHealth; const color = structure.buildingId === "command_relay" ? 0xf2c879 : this.bridge.content.buildings[structure.buildingId].defenseId ? 0xe07878 : 0x7396a3; this.world.fillStyle(health > 0 ? color : 0x35454b, 1).fillRect(structure.position.x - 18, structure.position.y - 18, 36, 36); this.world.lineStyle(1, 0x0b1115, 1).strokeRect(structure.position.x - 18, structure.position.y - 18, 36, 36); this.world.fillStyle(0x071017, .75).fillRect(structure.position.x - 22, structure.position.y + 25, 44, 5); this.world.fillStyle(0x8ee6d1, 1).fillRect(structure.position.x - 22, structure.position.y + 25, 44 * Math.max(0, Math.min(1, health / maxHealth)), 5); }
}

export { ARENA };
