import type { OrbitscarContent, OrbitscarEncounterDefinition, OrbitscarResourceBundle } from "@orbitscar/content";
import type { ColonyState, OrbitscarBattleResult } from "@orbitscar/simulation";
import { MAX_DEPLOYMENT_CHARGES, type GameSession } from "../state/game-session.js";

export type RenderContext = { root: HTMLElement; content: OrbitscarContent; colony: ColonyState; selectedTarget: OrbitscarEncounterDefinition; selectedBuildingId?: string; buildMode?: string; notice: string; session: GameSession };

function escapeHtml(value: string): string { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;"); }
function displayName(id: string): string { return escapeHtml(id.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase())); }
function bundleText(bundle: OrbitscarResourceBundle): string { return Object.entries(bundle).map(([id, value]) => `${displayName(id)} ${value}`).join(" · "); }
function button(label: string, action: string, className = "", disabled = false): string { return `<button type="button" class="${escapeHtml(className)}" data-action="${escapeHtml(action)}"${disabled ? " disabled" : ""}>${escapeHtml(label)}</button>`; }
function capacityOf(entries: Record<string, number>, content: OrbitscarContent): number { return Object.entries(entries).reduce((total, [unitId, count]) => total + count * (content.units[unitId]?.capacity ?? 0), 0); }
function stagedCount(session: GameSession, unitId: string): number { return session.plan.waves.reduce((total, wave) => total + (wave.units.find((entry) => entry.unitId === unitId)?.count ?? 0), 0); }
function resourceStrip(colony: ColonyState): string { return `<div class="resource-strip">${Object.entries(colony.resources).map(([id, value]) => `<div class="resource"><strong>${Math.floor(value)}</strong><span>${displayName(id)}</span></div>`).join("")}</div>`; }
function buildingRole(content: OrbitscarContent, buildingId: string): string { const building = content.buildings[buildingId]; if (building.targetTags.includes("core")) return "command core"; if (building.defenseId) return `defense · ${displayName(building.defenseId)}`; if (building.targetTags.includes("resource")) return "resource target"; return building.targetTags.join(" · "); }

function renderColony(context: RenderContext): string {
  const { content, colony, notice, buildMode, selectedBuildingId } = context;
  const selected = selectedBuildingId === undefined ? undefined : colony.buildings.find((building) => building.id === selectedBuildingId);
  return `<h1>Home colony</h1><p class="eyebrow">Landing plinth // persistent local authority</p>${resourceStrip(colony)}<div class="row"><span class="muted">Reserves</span><strong>${Object.values(colony.reserves).reduce((total, count) => total + count, 0)} units</strong></div><div class="actions">${button("Collect cycle", "collect")} ${button("Save colony", "save", "primary")} ${button("Choose target", "targets", "primary")}</div><div class="notice" role="status" aria-live="polite">${escapeHtml(notice)}</div><h2>Construction</h2><p>Select a module, then tap an open plinth cell to place it. Select an installed module to inspect and upgrade it.</p><div class="card-grid">${Object.values(content.buildings).map((building) => `<div class="card ${buildMode === building.id ? "selected" : ""}"><h3>${displayName(building.id)}</h3><div class="meta">${building.footprint.join("×")} grid · ${building.maxHealth} integrity · ${buildingRole(content, building.id)}</div><p>${bundleText(building.cost)}</p>${button(buildMode === building.id ? "Placement armed" : "Place module", `build:${building.id}`, buildMode === building.id ? "selected" : "")}</div>`).join("")}</div><h2>Installed modules</h2><div class="stack">${colony.buildings.map((building) => { const definition = content.buildings[building.buildingId]; const maxHealth = definition.maxHealth * (1 + (building.level - 1) * .25); return `<div class="card ${selectedBuildingId === building.id ? "selected" : ""}"><div class="row"><button type="button" class="building-select" data-action="select-building:${escapeHtml(building.id)}" aria-pressed="${selectedBuildingId === building.id}"><h3>${displayName(building.buildingId)}</h3><span class="meta">${escapeHtml(building.id)} · level ${building.level} · ${Math.round(building.health)} integrity</span></button>${button("Upgrade", `upgrade:${building.id}`)}</div><div class="meter"><i style="width:${Math.min(100, building.health / maxHealth * 100)}%"></i></div></div>`; }).join("")}</div>${selected ? `<div class="notice">Selected ${displayName(selected.buildingId)}. ${buildingRole(content, selected.buildingId)} · upgrade cost scales with level.</div>` : ""}<h2>Training bay</h2><div class="card-grid">${Object.values(content.units).map((unit) => `<div class="card"><h3>${displayName(unit.id)}</h3><div class="meta">${displayName(unit.role)} · capacity ${unit.capacity} · ${colony.reserves[unit.id] ?? 0} owned</div><p>${bundleText(unit.cost)}</p>${button("Train 1", `train:${unit.id}`)}</div>`).join("")}</div><p class="footer-help">Drag to pan · wheel or two-finger pinch to zoom · save persists a local snapshot.</p>`;
}

function renderTargets(context: RenderContext): string {
  const { content, selectedTarget } = context;
  return `<h1>Sector targets</h1><p>Scout an authored relay snapshot before committing reserves. Inspect approach lanes, roles, exposed resources, counter hints, and the full-breach salvage preview.</p><div class="card-grid">${Object.values(content.encounters).map((target) => `<div class="card ${target.id === selectedTarget.id ? "selected" : ""}"><div class="row"><h3>${escapeHtml(target.name)}</h3><span class="pill">${escapeHtml(target.difficulty)}</span></div><div class="meta">${escapeHtml(target.codename)} · ${target.structures.length} structures</div><p>${escapeHtml(target.description)}</p><div class="scout-map" aria-label="${escapeHtml(target.name)} layout">${target.structures.map((structure) => `<span class="scout-node ${content.buildings[structure.buildingId].defenseId ? "defense" : "target"}" style="left:${Math.min(94, structure.position.x / 12)}%;top:${Math.min(90, structure.position.y / 8)}%" title="${escapeHtml(structure.id)} — ${escapeHtml(buildingRole(content, structure.buildingId))}">${escapeHtml(structure.id)}</span>`).join("")}</div><p class="meta">Fire lanes: ${target.structures.filter((structure) => content.buildings[structure.buildingId].defenseId).map((structure) => `${escapeHtml(structure.id)} ${content.buildings[structure.buildingId].defenseId ? `(${content.defenses[content.buildings[structure.buildingId].defenseId!].range} range)` : ""}`).join(" · ") || "none"}</p><p class="meta">Exposed resources: ${target.structures.filter((structure) => content.buildings[structure.buildingId].targetTags.includes("resource")).map((structure) => escapeHtml(structure.id)).join(", ") || "none"}</p><p class="meta">Counter hints: ${target.suggestedCounters.map(displayName).join(" · ")}</p><p class="reward">Full-breach salvage: ${bundleText(target.rewardPreview)}</p>${button(target.id === selectedTarget.id ? "Scouted target" : "Scout target", `scout:${target.id}`, target.id === selectedTarget.id ? "primary" : "")}</div>`).join("")}</div><div class="actions">${button("Compose attacking force", "army", "primary")} ${button("Back to colony", "colony")}</div>`;
}

function renderArmy(context: RenderContext): string {
  const { content, selectedTarget, session, notice } = context;
  const capacity = capacityOf(session.plan.selectedArmy, content);
  return `<h1>Compose breach force</h1><p>Choose from persistent reserves. Every unit consumes deployment capacity; the resolver remains authoritative.</p><div class="row"><span class="muted">Target</span><strong>${escapeHtml(selectedTarget.name)}</strong></div><div class="row"><span class="muted">Capacity</span><strong>${capacity} / 10</strong></div><div class="meter"><i style="width:${Math.min(100, capacity * 10)}%"></i></div><div class="stack" style="margin-top:12px">${Object.values(content.units).map((unit) => { const count = session.plan.selectedArmy[unit.id] ?? 0; return `<div class="card"><div class="row"><div><h3>${displayName(unit.id)}</h3><div class="meta">${displayName(unit.role)} · ${context.colony.reserves[unit.id] ?? 0} reserve · ${unit.capacity} capacity each</div></div><div class="quantity">${button("−", `army:-:${unit.id}`)}<output aria-label="${displayName(unit.id)} selected">${count}</output>${button("+", `army:+:${unit.id}`, "", count >= (context.colony.reserves[unit.id] ?? 0) || capacity + unit.capacity > 10)}</div></div></div>`; }).join("")}</div><div class="actions">${button("Back to targets", "targets")} ${button("Begin deployment", "begin-deployment", "primary", capacity === 0)}</div><div class="notice" role="status">${escapeHtml(notice)}</div>`;
}

function renderDeployment(context: RenderContext): string {
  const { content, selectedTarget, session } = context;
  const nextCapacity = capacityOf(session.plan.waveDraft, content);
  const canDeploy = Object.values(session.plan.waveDraft).some((count) => count > 0) && session.plan.waves.length < MAX_DEPLOYMENT_CHARGES;
  return `<h1>Choose the breach</h1><p>Commit the first approach, then use later windows for deterministic reinforcement. Deployment timing is recorded as simulation ticks.</p><div class="card"><div class="row"><strong>${escapeHtml(selectedTarget.name)}</strong><span class="pill">${session.plan.waves.length} / ${MAX_DEPLOYMENT_CHARGES} waves staged</span></div><p class="meta">Next wave: ${Object.values(session.plan.waveDraft).reduce((total, count) => total + count, 0)} units · ${nextCapacity} / 10 capacity</p></div><h2>Deployment point</h2><div class="zone-grid">${(["west", "north", "south", "east"] as const).map((zone) => button(zone.toUpperCase(), `zone:${zone}`, session.plan.selectedZone === zone ? "selected" : "")).join("")}</div><h2>Wave ${session.plan.waves.length + 1}</h2><div class="stack">${Object.values(content.units).filter((unit) => (session.plan.waveDraft[unit.id] ?? 0) > 0).map((unit) => `<div class="row"><span>${displayName(unit.id)} <span class="meta">(${unit.capacity} cap · ${stagedCount(session, unit.id)} staged)</span></span><div class="quantity">${button("−", `wave:-:${unit.id}`)}<output>${session.plan.waveDraft[unit.id] ?? 0}</output>${button("+", `wave:+:${unit.id}`, "", (session.plan.waveDraft[unit.id] ?? 0) >= (session.plan.selectedArmy[unit.id] ?? 0) - stagedCount(session, unit.id) || nextCapacity + unit.capacity > 10)}</div></div>`).join("") || `<div class="empty">All selected units are staged.</div>`}</div>${session.plan.waves.length > 0 ? `<div class="card staged-waves"><strong>Staged waves</strong>${session.plan.waves.map((wave, index) => `<p class="meta">Wave ${index + 1} · ${wave.zone.toUpperCase()} · ${wave.units.map((entry) => `${displayName(entry.unitId)} ×${entry.count}`).join(", ")}</p>`).join("")}</div>` : ""}<div class="actions">${button("Deploy wave", "deploy-wave", "primary", !canDeploy)} ${button(session.plan.abilityArmed ? "Reroute armed" : "Arm Emergency Reroute", "ability", session.plan.abilityArmed ? "warn" : "")} ${button("Resolve autonomous battle", "resolve-battle", "primary", session.plan.waves.length === 0)} ${button("Cancel", "cancel-deployment")}</div><p class="footer-help">Choose a marked approach. A fourth wave is unavailable by design.</p>`;
}

function renderBattle(context: RenderContext): string {
  const replay = context.session.replay;
  if (replay === undefined) return "<h1>Deployment unavailable</h1>";
  const progress = Math.min(100, replay.result.durationTicks === 0 ? 100 : Math.max(0, replay.result.events[Math.max(0, replay.eventIndex - 1)]?.tick ?? 0) / replay.result.durationTicks * 100);
  const latest = replay.result.events[Math.max(0, replay.eventIndex - 1)];
  return `<h1>Autonomous breach</h1><p>${escapeHtml(context.selectedTarget.name)} · the plan is locked. Watch the deterministic event stream resolve.</p><div class="meter"><i style="width:${progress}%"></i></div><p class="meta">${latest ? `Tick ${latest.tick}: ${displayName(latest.type)}${latest.entityId ? ` · ${escapeHtml(latest.entityId)}` : ""}` : "Awaiting first deployment…"}</p><div class="event-log" aria-live="polite">${replay.result.events.slice(Math.max(0, replay.eventIndex - 9), replay.eventIndex).map((event) => `${event.tick.toString().padStart(4, "0")}  ${escapeHtml(event.type)}${event.entityId ? `  ${escapeHtml(event.entityId)}` : ""}`).join("<br>") || "Awaiting event stream…"}</div><div class="actions">${button(replay.done ? "Open battle report" : "Replay running…", "report", "primary", !replay.done)} ${button("Retreat", "retreat", "warn", replay.done)} ${button("Restart plan", "restart-plan")}</div>`;
}

function tacticalReadout(result: OrbitscarBattleResult, context: RenderContext): string {
  const damagedDefenses = Object.entries(result.damageByEntity).filter(([id]) => context.selectedTarget.structures.some((structure) => structure.id === id && context.content.buildings[structure.buildingId].defenseId));
  const topDefense = damagedDefenses.sort(([, left], [, right]) => right - left)[0]?.[0];
  const topAttacker = Object.entries(result.damageByEntity).filter(([id]) => id.includes("#")).sort(([, left], [, right]) => right - left)[0]?.[0];
  const lossText = Object.entries(result.attackerCasualties).filter(([, count]) => count > 0).map(([id, count]) => `${displayName(id)} ×${count}`).join(", ") || "no attacker losses";
  return `${result.retreated ? "The commander ordered a retreat before resolution. " : ""}${topDefense ? `${displayName(topDefense)} absorbed the most recorded damage (${result.damageByEntity[topDefense]}). ` : "No defense damage was recorded. "}${topAttacker ? `${displayName(topAttacker.split("#")[0])} was the most productive recorded attacker. ` : ""}Losses: ${lossText}.`;
}

function renderReport(context: RenderContext): string {
  const result = context.session.replay?.result;
  if (!result) return `<h1>No report</h1>${button("Return home", "colony", "primary")}`;
  const totalDeployed = result.deploymentUsage.reduce((sum, usage) => sum + usage.units.reduce((inner, unit) => inner + unit.count, 0), 0);
  const casualties = Object.values(result.attackerCasualties).reduce((sum, count) => sum + count, 0);
  return `<h1>Battle report</h1><p class="eyebrow">${escapeHtml(context.selectedTarget.codename)} · attempt ${escapeHtml(context.session.replay?.attemptId ?? "unknown")}</p><div class="card ${result.winner === "attacker" ? "selected" : ""}"><div class="row"><h3>${result.retreated ? "Force withdrawn" : result.victoryTier === "full" ? "Relay secured" : result.victoryTier === "partial" ? "Partial breach" : "Defense held"}</h3><span class="pill">${escapeHtml(result.victoryTier)}</span></div><p>${result.retreated ? "The force withdrew and keeps its surviving units; this attempt generated no salvage." : result.winner === "attacker" ? "Your route reached the hostile core." : "The relay held, but the event stream is preserved for the next plan."}</p></div><div class="resource-strip"><div class="resource"><strong>${totalDeployed}</strong><span>deployed</span></div><div class="resource"><strong>${casualties}</strong><span>casualties</span></div><div class="resource"><strong>${result.destroyedStructureIds.length}</strong><span>structures down</span></div></div><h2>Salvage</h2><p>${Object.keys(result.loot).length === 0 ? "No salvage recovered." : bundleText(result.loot)}</p><h2>Tactical readout</h2><p>${escapeHtml(tacticalReadout(result, context))}</p><p class="meta">Duration ${result.durationTicks} ticks · ${result.eventCount} events · replay ${escapeHtml(result.canonicalHash.slice(0, 12))}…</p><div class="actions">${button("Return to colony and apply result", "return-home", "primary")} ${button("Attack again", "attack-again")}</div><div class="notice">This attempt is applied once by its attempt ID; deterministic hashes verify what happened.</div>`;
}

export function renderApp(context: RenderContext): void {
  const { content, colony, session } = context;
  const activeMode = session.mode;
  const body = activeMode === "colony" ? renderColony(context) : activeMode === "targets" ? renderTargets(context) : activeMode === "army" ? renderArmy(context) : activeMode === "deployment" ? renderDeployment(context) : activeMode === "battle" ? renderBattle(context) : renderReport(context);
  context.root.innerHTML = `<div class="shell"><header class="topbar"><div class="brand">ORBITSCAR</div><div class="eyebrow">orbital frontier command</div><nav class="nav" aria-label="Primary">${(["colony", "targets", "army"] as const).map((item) => `<button type="button" class="${activeMode === item ? "active" : ""}" data-action="${item}">${displayName(item)}</button>`).join("")}</nav><div class="metrics">ALLOY ${Math.floor(colony.resources.alloy ?? 0)} · VOL ${Math.floor(colony.resources.volatile ?? 0)} · SIG ${Math.floor(colony.resources.signal ?? 0)}</div></header><section class="content ${activeMode === "battle" || activeMode === "report" ? "wide" : ""}">${body}</section></div>`;
}
